# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c5a90164757793354bcd6f7028b8371d226a72c1acd17faa73e71cbe4aed965dcd6dce87997d18ef477e585393a5daab09f05c237c8b2b0b61b907efac42d4f

test:
  secret_key_base: 9a4531abdc619f9b01cbe2833634f7442195d6f8a74d1e49bc622e103c56b5d743e28b3e7cca15543101b9f93805356fd2871e47aae0e24d3e3bae4895e82258

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
